### ISSUE TITLE
I can't  sign in with my client-id

### ISSUE THREAD

**Issue by seucr** [googlesamples/weave-ledflasher-web#1]
Hi, I am trying to use weave led flasher. After I type in "gulp" in console, the browser just showup and asked me to "Sign in". However, the browser didn't asked me to type in my account after I pressed the "Sign in" button.  I think there should be an account for me to sign in. Is there a default one? Or how can I modify it?

BTW, if I didn't change the client-id index.html, seems I can successfully pass Oauth and signed in. But If I replaced client-id with mine, I can't signed in with the following message:
"
401. That’s an error.

Error: invalid_client

The OAuth client was not found.
Request Details

    openid.realm=
    scope=email profile https://www.googleapis.com/auth/weave.app openid
    response_type=permission
    redirect_uri=storagerelay://http/localhost:5001?id=auth78330
    ss_domain=http://localhost:5001
    client_id=58855807228.apps.googleusercontent.com
    fetch_basic_profile=true

That’s all we know.
"
Do you have any idea about this problem?

Thanks very much!

**Comment by pengying** [comment]
Yeah you have to replace the client-id in index.html with your client id.  Also you need to be whitelisted for Weave.

**Comment by seucr** [comment]
Thanks very much. I think I misunderstood Oauth2 procedure.
